import Sidebar from '@/components/Sidebar'
import './globals.css'
import type { Metadata } from 'next'
import {Oxygen} from 'next/font/google'
import Player from '@/components/Player'

const font = Oxygen({ subsets: ['latin'], weight: ['300', '400' , '700'] })

export const metadata: Metadata = {
  title: 'Music Web App',
  description: 'Generated by Mohammad Karami',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
      <Sidebar>
        {children}
      </Sidebar>
      <Player />
        </body>
    </html>
  )
}
